### PR TITLE
Enumerable methods

### PR DESCRIPTION
**Pull request by PhillipUg**
## In this project, i have done the following:
- Added my new enumerable methods into the existing enumerable module
- Tested all my methods to ensure they work as expected
- Used `rubocop` to enforce development guidelines

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Phillip!  
### You did a great job so far :+1: 
Here are things you need to fix before this project can be approved:
* [x] Stickler is not checking this Pull request, make sure that you set up everything correctly.
###  My_all?
* [x] When no block or argument is given should return true if at least one of the collection is not false or nil. For example:
`[1, false, 'hi', []].my_all?` - should return false

* [x]  When a class is passed as an argument should return true if all of the collection is a member of such class. For example:
`[1, 'dog', []].my_all?(Integer)` - should return false
### My_any?
* [x] When no block or argument is given should return true if at least one of the collection is not false or nil. For example:
`[nil, false, nil, false].my_any?` - should return false

* [x] When a class is passed as an argument should return true if at least one of the collection is a member of such class. For example:
`[1, 2, 3, 4, 5].my_any?(Integer)` - should return true

* [x] When a pattern other than Regex or a Class is given should return false if none of the collection matches the pattern. For example:
`['dog', 'bird', 'fish'].my_any?('dog')` - should return true
### My_none

* [x] When no block or argument is given should return true only if none of the collection members is true. For example:
`[nil, false, nil, false].my_none?` - should return true

* [x] When a class is passed as an argument should return true if none of the collection is a member of such class. For example:
[1, 2 ,3].my_none?(String) - should return false

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by PhillipUg** [comment]
Thanks @pelzolga123 for the timely review. Let me work on fixing the issues you've raised

**Comment by PhillipUg** [comment]
In this project, i have done the following:
Added my new enumerable methods into the existing enumerable module
Tested all my methods to ensure they work as expected
Used rubocop to enforce development guidelines

**Comment by PhillipUg** [comment]
I have worked on the suggested changes.

**Comment by PhillipUg** [comment]
I have worked on the suggested changes.

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Comment by PhillipUg** [comment]
Thanks for the timely review @stratospherique

**Pull request merged**
